/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Spec.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
nfsprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		Pair register_1_arg;
		Pair login_1_arg;
		input ls_1_arg;
		input cd_1_arg;
		input mkdir_1_arg;
		input mkfile_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case register:
		_xdr_argument = (xdrproc_t) xdr_Pair;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) register_1_svc;
		break;

	case login:
		_xdr_argument = (xdrproc_t) xdr_Pair;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) login_1_svc;
		break;

	case ls:
		_xdr_argument = (xdrproc_t) xdr_input;
		_xdr_result = (xdrproc_t) xdr_lsresult;
		local = (char *(*)(char *, struct svc_req *)) ls_1_svc;
		break;

	case cd:
		_xdr_argument = (xdrproc_t) xdr_input;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) cd_1_svc;
		break;

	case mkdir:
		_xdr_argument = (xdrproc_t) xdr_input;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) mkdir_1_svc;
		break;

	case mkfile:
		_xdr_argument = (xdrproc_t) xdr_input;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) mkfile_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (NFSPROG, NFSVERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, NFSPROG, NFSVERSION, nfsprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (NFSPROG, NFSVERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, NFSPROG, NFSVERSION, nfsprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (NFSPROG, NFSVERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
