/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SPEC_H_RPCGEN
#define _SPEC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *filename;

typedef char *argument;

struct input {
	char command[20];
	argument arr[10];
	int lenarr;
};
typedef struct input input;

struct Pair {
	char *username;
	char *password;
};
typedef struct Pair Pair;

struct lsresult {
	filename arr[50];
	int num;
};
typedef struct lsresult lsresult;

#define NFSPROG 0x21111111
#define NFSVERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define register 1
extern  int * register_1(Pair *, CLIENT *);
extern  int * register_1_svc(Pair *, struct svc_req *);
#define login 2
extern  int * login_1(Pair *, CLIENT *);
extern  int * login_1_svc(Pair *, struct svc_req *);
#define ls 3
extern  lsresult * ls_1(input *, CLIENT *);
extern  lsresult * ls_1_svc(input *, struct svc_req *);
#define cd 4
extern  int * cd_1(input *, CLIENT *);
extern  int * cd_1_svc(input *, struct svc_req *);
#define mkdir 5
extern  int * mkdir_1(input *, CLIENT *);
extern  int * mkdir_1_svc(input *, struct svc_req *);
#define mkfile 6
extern  int * mkfile_1(input *, CLIENT *);
extern  int * mkfile_1_svc(input *, struct svc_req *);
extern int nfsprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define register 1
extern  int * register_1();
extern  int * register_1_svc();
#define login 2
extern  int * login_1();
extern  int * login_1_svc();
#define ls 3
extern  lsresult * ls_1();
extern  lsresult * ls_1_svc();
#define cd 4
extern  int * cd_1();
extern  int * cd_1_svc();
#define mkdir 5
extern  int * mkdir_1();
extern  int * mkdir_1_svc();
#define mkfile 6
extern  int * mkfile_1();
extern  int * mkfile_1_svc();
extern int nfsprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_filename (XDR *, filename*);
extern  bool_t xdr_argument (XDR *, argument*);
extern  bool_t xdr_input (XDR *, input*);
extern  bool_t xdr_Pair (XDR *, Pair*);
extern  bool_t xdr_lsresult (XDR *, lsresult*);

#else /* K&R C */
extern bool_t xdr_filename ();
extern bool_t xdr_argument ();
extern bool_t xdr_input ();
extern bool_t xdr_Pair ();
extern bool_t xdr_lsresult ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SPEC_H_RPCGEN */
