/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Spec.h"

bool_t
xdr_filename (XDR *xdrs, filename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_argument (XDR *xdrs, argument *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 20))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_input (XDR *xdrs, input *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->command, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->arr, 10,
		sizeof (argument), (xdrproc_t) xdr_argument))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->lenarr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Pair (XDR *xdrs, Pair *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, 50))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->password, 20))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lsresult (XDR *xdrs, lsresult *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->arr, 50,
		sizeof (filename), (xdrproc_t) xdr_filename))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num))
		 return FALSE;
	return TRUE;
}
