/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Spec.h"

int *
operate_1_svc(Operation *argp, struct svc_req *rqstp)
{
	static int  result;

	switch(argp->op)
	{
		case 1:
		result = argp->op1+argp->op2;
		break;
		case 2:
		result = argp->op1-argp->op2;
		break;
		case 3:
		result = argp->op1*argp->op2;
		break;
		case 4:
		result = argp->op1/argp->op2;
		break;
	}


	return &result;
}
