/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Spec.h"


void
mathprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	Operation  operate_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MATHPROG, INITIAL, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("Enter two operans and one operator\n");
	scanf("%d%d%d",&operate_1_arg.op1,&operate_1_arg.op2,&operate_1_arg.op);
	result_1 = operate_1(&operate_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("Result is: %d\n",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	mathprog_1 (host);
exit (0);
}
