/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Spec.h"

bool_t
xdr_Operation (XDR *xdrs, Operation *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->op1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->op2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->op))
		 return FALSE;
	return TRUE;
}
