/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SPEC_H_RPCGEN
#define _SPEC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Operation {
	int op1;
	int op2;
	int op;
};
typedef struct Operation Operation;

#define MATHPROG 0x21111111
#define INITIAL 1

#if defined(__STDC__) || defined(__cplusplus)
#define operate 1
extern  int * operate_1(Operation *, CLIENT *);
extern  int * operate_1_svc(Operation *, struct svc_req *);
extern int mathprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define operate 1
extern  int * operate_1();
extern  int * operate_1_svc();
extern int mathprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Operation (XDR *, Operation*);

#else /* K&R C */
extern bool_t xdr_Operation ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SPEC_H_RPCGEN */
